export const CURRICULUM_COURSES = [
  { code: '1GES92', name: 'Taller de Habilidades Interpersonales', ciclo: 5, creditos: 1 },
  { code: '1IND90', name: 'Empresa y su Entorno', ciclo: 5, creditos: 2 },
  { code: '1INF25', name: 'Programación 2', ciclo: 5, creditos: 5 },
  { code: '1INF27', name: 'Algoritmia y Estructura de Datos', ciclo: 5, creditos: 3.5 },
  { code: '1INF28', name: 'Fundamentos de Sistemas de Información', ciclo: 5, creditos: 3.5 },
  { code: '1INF33', name: 'Base de Datos', ciclo: 5, creditos: 3.5 },
  { code: '1INF49', name: 'Ingeniería de Requisitos', ciclo: 5, creditos: 3.5 },
  { code: '1CON27', name: 'Contabilidad y Finanzas', ciclo: 6, creditos: 2.5 },
  { code: '1ELE01', name: 'Arquitectura de Computadoras', ciclo: 6, creditos: 3.5 },
  { code: '1EST22', name: 'Probabilidad y Estadística', ciclo: 6, creditos: 3.5 },
  { code: '1INF29', name: 'Sistemas Operativos', ciclo: 6, creditos: 2.5 },
  { code: '1INF30', name: 'Programación 3', ciclo: 6, creditos: 5 },
  { code: '1INF31', name: 'Arquitectura de Software', ciclo: 6, creditos: 2.5 },
  { code: '1INF32', name: 'Algoritmos Avanzados', ciclo: 6, creditos: 2.5 },
  { code: '1EST14', name: 'Experimentación Numérica', ciclo: 7, creditos: 2 },
  { code: '1INF24', name: 'Inteligencia Artificial', ciclo: 7, creditos: 3.5 },
  { code: '1INF34', name: 'Modelado y Automatización de Procesos Empresariales', ciclo: 7, creditos: 3.5 },
  { code: '1INF35', name: 'Administración de Sistemas Operativos', ciclo: 7, creditos: 2.5 },
  { code: '1INF50', name: 'Diseño de Software', ciclo: 7, creditos: 2.5 },
  { code: '1IND231', name: 'Ingeniería Económica', ciclo: 7, creditos: 3.5 },
  { code: '1INF238', name: 'Redes de Computadoras', ciclo: 7, creditos: 4 },
  { code: '1INF26', name: 'Formulación de Proyecto de Fin de Carrera', ciclo: 8, creditos: 2 },
  { code: '1INF36', name: 'Ética y RSU en Ingeniería Informática', ciclo: 8, creditos: 2.5 },
  { code: '1INF37', name: 'Ingeniería de Software', ciclo: 8, creditos: 3.5 },
  { code: '1INF38', name: 'Innovación y Emprendimiento con TI', ciclo: 8, creditos: 3 },
  { code: '1INF39', name: 'Gobierno y Gestión de TI', ciclo: 8, creditos: 3.5 },
  { code: '1INF40', name: 'Tecnologías de Información para los Negocios', ciclo: 8, creditos: 3.5 },
  { code: '1INF41', name: 'Seguridad de Información', ciclo: 8, creditos: 3.5 },
  { code: '1INF42', name: 'Proyecto de Fin de Carrera 1', ciclo: 9, creditos: 2 },
  { code: '1INF44', name: 'Arquitectura Empresarial', ciclo: 9, creditos: 3 },
  { code: '1INF45', name: 'Implantación de Sistemas de Información', ciclo: 9, creditos: 3 },
  { code: '1INF54', name: 'Proyecto de Diseño y Desarrollo de Software', ciclo: 9, creditos: 3 },
  { code: '1IND328', name: 'Gestión de Proyectos', ciclo: 9, creditos: 3 },
  { code: '1INF008', name: 'Práctica Supervisada Preprofesional 1', ciclo: 9, creditos: 0.5 },
  { code: '1INF46', name: 'Proyecto de Fin de Carrera 2', ciclo: 10, creditos: 2 },
  { code: '1INF47', name: 'Proyecto de Implementación de Software', ciclo: 10, creditos: 3 },
  { code: '1INF48', name: 'Estrategia y Gestión de Sistemas de Información', ciclo: 10, creditos: 3.5 },
];
